title: Kevin's Blog
author: Kevin Guerrero
email: kmg201@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Checkout my blog for awesome portfolios of ideas and inventions. 
# social links
twitter_username: allinoneinvent
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
